# Generated by Django 2.1.15 on 2020-12-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingrediant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingrediant',
            new_name='Ingredient',
        ),
    ]
